apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-deployment
  namespace: devops-blog


spec:
  replicas: 2

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
  
    spec:
      containers:
      - name: backend
        image: jaydipaws/devops-blog-backend:v2
        

        ports:
        - containerPort: 8080

        env: 
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MONGO_URL

        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USERNAME


        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD

                

        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
          
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
